<?php

namespace Shortio\Laravel\Api;

class Domain extends Api
{

    protected $path = 'api/domains';

    public function prepareUpdateUrl($id)
    {
        return parent::prepareUpdateUrl("settings/$id"); // TODO: Change the autogenerated stub
    }
}