<?php

namespace Shortio\Laravel\Api;

class Domain extends Api
{

    public function prepareUpdateUrl($id)
    {
        return parent::prepareUpdateUrl("settings/$id"); // TODO: Change the autogenerated stub
    }
}