<?php

namespace Shortio\Laravel\Api;

use Illuminate\Support\Facades\Http;

class Shortio extends Http
{

    public static function baseUrl(string $url)
    {
        parent::baseUrl(static::uri($url)); // TODO: Change the autogenerated stub
    }

    protected static function uri(string $url)
    {
        $class = (new \ReflectionClass(self))->getShortName();

        $base = '';
        if ($class !== 'Shortio') {
            $base = strtolower($class);
        }

        return config('shortio.api')."/$base";
    }
}
